flaskApp_env/App/flaskapp_env/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    post_content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class SearchForm(FlaskForm):
    searched = StringField('Searched',
                        validators=[DataRequired()])
    submit = SubmitField('Submit')

flaskApp_env/App/flaskapp_env/main/routes.py
from flask import render_template, request, Blueprint
from flaskapp_env.modules_TIA import Post
main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page',1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)

@main.route('/about')
def about():
    return render_template('about.html', title='About')

flaskApp_env/App/flaskapp_env/posts/routes.py
from flask import flash, redirect, render_template, url_for, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskapp_env import db
from flaskapp_env.posts.forms import PostForm, SearchForm
from flaskapp_env.modules_TIA import Post

posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, post_content=form.post_content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!','success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', 
                        form=form, legend='New Post')

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.post_content = form.post_content.data
        db.session.commit()
        flash('Your post has been updated!','success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method =='GET':
        form.title.data = post.title
        form.post_content.data = post.post_content
    return render_template('create_post.html', title='Update Post', 
                        form=form, legend='Update Post')
 
@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
#refer. <form action="{{ url_for('delete_post', post_id=post.id) }}" method="POST">
def delete_post(post_id): 
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!','success')
    return redirect(url_for('main.home'))

#PASS stuff to Navbar
@posts.app_context_processor
def base():
    form = SearchForm()
    return dict(form=form)
    
@posts.route('/search', methods=["POST"])
def search():
     form = SearchForm()
     posts = Post.query
     if form.validate_on_submit():
        page = request.args.get('page',1, type=int)
        post.searched = form.searched.data
        posts = posts.filter(Post.post_content.like('%' + post.searched + '%'))
        posts = posts.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        
        return render_template("search.html", 
                form=form, 
                searched=post.searched,
                posts = posts)

flaskApp_env/App/flaskapp_env/users/routes.py
import pandas as pd
import csv
from datetime import date
from flask import app, flash, redirect, render_template, url_for, request, Blueprint, jsonify
from flask_login import login_user, current_user, logout_user, login_required
from werkzeug.datastructures import UpdateDictMixin
from flaskapp_env import  db, bcrypt
from flaskapp_env.users.utils_db import get_usable_data
from flaskapp_env.modules_TIA import (Member, Post, Country, Membership)
from flaskapp_env.users.forms import (AdminForm, MemberListForm, RegistrationForm, LoginForm, UpdateAccountForm
                        , RequestResetForm, ResetPasswordForm, AccountVerifiForm, UploadFileForm
                        , UploadFileToDBForm)
from flaskapp_env.users.utils import (save_picture, send_reset_email, send_account_verification
                        , upload_csv_file, parseCSV)

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    countries=db.session.query(Country).all()
    form.country_code.choices = [(i.CountryCode, i.CountryNameEN) for i in countries]  
    membership_type=db.session.query(Membership).all()
    form.membership_type.choices = [(i.ID, i.MembershipName) for i in membership_type]  
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        _memberid, _period = get_usable_data(4)
        member = Member(Member_ID=_memberid,
                        Period=_period,
                        Name=form.username.data,
                        MainMemberId='',
                        MembershipType=form.membership_type.data,
                        Email1=form.email.data, 
                        Email2='',
                        Email3='',
                        Email4='',
                        Phone1='',
                        Phone2='',
                        Phone3='',
                        Phone4='',
                        Password=hashed_password, 
                        NationalCode=form.country_code.data, 
                        MembershipChangedPeriod='',
                        Comment='')
        user = Member.query.filter_by(Email1=form.email.data).first()
        if user is None:
            db.session.add(member)
            db.session.commit()
        
        #Send Account Verification
        user = Member.query.filter_by(Email1=form.email.data).first()
        send_account_verification(user)
        flash('An email has been sent with account verification to activate your account.', 'info')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        member = Member.query.filter_by(Email1=form.email.data,Activate=1).first()
        if member and bcrypt.check_password_hash(member.Password, form.password.data):
            login_user(member, remember=form.remember.data)
             #argus is dictionary
             #為了確保如果在link上面沒有next字樣，若使用key去尋找時會出錯
             #所以使用get來搜尋，找不到next時就會回傳null
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Pleach check email and password!','danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    countries=db.session.query(Country).all()
    membership_type=db.session.query(Membership).all()
    form = UpdateAccountForm()
    form.country_code.choices = [(i.CountryCode, i.CountryName) for i in countries]
    form.membership_type.choices = [(i.ID, i.MembershipName) for i in membership_type]  

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.Image_file = picture_file
        current_user.Member_ID = form.memberid.data
        current_user.Name = form.username.data
        current_user.Email1 = form.email.data
        current_user.NationalCode = form.country_code.data
        current_user.MembershipType = form.membership_type.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.Name
        # form.XXXX 指label，內容的話要.data
        form.memberid.data = current_user.Member_ID
        form.email.data = current_user.Email1
        form.country_code.data = current_user.NationalCode
        form.membership_type.data = current_user.MembershipType
    image_file = url_for('static', filename='profile_pics/' + current_user.Image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page',1, type=int)
    member = Member.query.filter_by(Name=username).first_or_404()
    posts = Post.query.filter_by(author=member)\
            .order_by(Post.date_posted.desc())\
            .paginate(page=page , per_page=5)
    return render_template('user_posts.html', posts=posts,user=member)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Member.query.filter_by(Email1=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password',form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = Member.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired link', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.Password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password',form=form)

@users.route('/activate_account/<token>', methods=['GET', 'POST'])
def activate_account(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = Member.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired link', 'warning')
        return redirect(url_for('users.login'))
    form = AccountVerifiForm()
    if form.validate_on_submit():
        user.Activate = 1
        db.session.commit()
        flash('Your account has been activated! You are now able to login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('activate_account.html', title='Submit Account Verification',form=form)


@users.route("/upload", methods=['GET', 'POST'])
def upload():
    form = UploadFileForm()
    if form.validate_on_submit():
        if form.csvfile.data:
            f = upload_csv_file(form.csvfile.data)
            data = parseCSV(f)  
        flash('Upload data', 'success')
        subform = UploadFileToDBForm()
        return render_template('data.html', data=data, form=subform)
    return render_template('csv_upload.html', form=form)
        


@users.route("/upload_data", methods=['GET', 'POST'])
def data():
    #   # get the uploaded file
    # uploaded_file = request.files['csvfile']
    # if request.method == 'POST':
    #     f = upload_csv_file(uploaded_file)
    #     data = parseCSV(f)  
    #     # with open(f) as file:
    #     #     csvfile = csv.reader(file)
    #     #     for row in csvfile:
    #     #         data.append(row)
    return render_template('data.html', data=data)

@users.route('/admin')
@login_required
def admin():
    form = AdminForm()
    if current_user.is_authenticated:
        return render_template('admin.html', form=form)

@users.route('/admin/member')
@login_required
def members():
    form = MemberListForm()
    if current_user.is_authenticated:
        members = Member.query.filter().all()
        return render_template('member_list.html', form=form, members=members)

flaskApp_env/App/flaskapp_env/templates/activate_account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Activate Account</legend>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskApp_env/App/flaskapp_env/templates/admin.html
{% extends "layout.html" %}
{% block content %}
    <h1> Admin!!!!</h1>
    <a class="nav-item nav-link" href="{{ url_for('users.members') }}">Member List</a>
{% endblock content %}

flaskApp_env/App/flaskapp_env/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Taiwan Ireland lab - {{ title }}</title>
    {% else %}
        <title>Taiwan Ireland lab</title>
    {% endif%}
</head>
<body>
    
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Taiwanese Cuisine</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
              <!-- Navbar Right Side -->
                <ul div class="navbar-nav">
                  {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.upload') }}">Upload</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.admin') }}">Admin</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
                </ul>
              </div>
              <form method="POST" action="{{ url_for('posts.search') }}" class="d-flex">
                {{ form.hidden_tag() }}
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                </ul>
              </p>
            </div>
          </div>

        </div>
      </main>
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    <!-- for the Bootstrap Modal 互動視窗 -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

</body>
</html>

flaskApp_env/App/flaskapp_env/templates/layout_TW.html
<!DOCTYPE html>
<html lang="zh-Hant">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>廚藝實驗室 - {{ title }}</title>
    {% else %}
        <title>廚藝實驗室</title>
    {% endif%}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">廚藝實驗室</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">首頁</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">關於</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">新貼文</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">會員</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">登出</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">登入</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">註冊</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">最新文章</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">行程表</li>
                  <li class="list-group-item list-group-item-light">等等</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    <!-- for the Bootstrap Modal 互動視窗 -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

</body>
</html>

flaskApp_env/App/flaskapp_env/templates/layout_nosidebar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Taiwan Ireland lab - {{ title }}</title>
    {% else %}
        <title>Taiwan Ireland lab</title>
    {% endif%}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Taiwanese Cuisine</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                  <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                  <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
              <!-- Navbar Right Side -->
                <ul div class="navbar-nav">
                  {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.upload') }}">Upload</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.admin') }}">Admin</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
                </ul>
              </div>
              <form method="POST" action="{{ url_for('posts.search') }}" class="d-flex">
                {{ form.hidden_tag() }}
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8"> 
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          </div>
          {% block content %}{% endblock %}
        </div>
      </main>
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    <!-- for the Bootstrap Modal 互動視窗 -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

</body>
</html>